# This note book contains - Creating, Reading and Writing

## Data Frame

In [1]:
import pandas as pd

In [2]:
pd.DataFrame({'Yes': [50, 21], 'No': [131, 2]})

   Yes   No
0   50  131
1   21    2

In [6]:
pd.DataFrame({'Fahad':['setu','muntaha','aysha','aru'],'Afif':['Maria','Adrita','Noboti','Sadia']},index=['a','b','c','d'])

     Fahad    Afif
a     setu   Maria
b  muntaha  Adrita
c    aysha  Noboti
d      aru   Sadia

In [8]:
pd.DataFrame({'Bob': ['I liked it.', 'It was awful.'], 'Sue': ['Pretty good.', 'Bland.']})

             Bob           Sue
0    I liked it.  Pretty good.
1  It was awful.        Bland.

In [9]:
pd.DataFrame({'Bob': ['I liked it.', 'It was awful.'], 
              'Sue': ['Pretty good.', 'Bland.']},
             index=['Product A', 'Product B'])

                     Bob           Sue
Product A    I liked it.  Pretty good.
Product B  It was awful.        Bland.

In [10]:
Gandu = pd.DataFrame({'Sec A': ['A','B','C','D'],'Sec B':['e','f','g','h']},index=['one','two','three','four'])

In [11]:
Gandu

      Sec A Sec B
one       A     e
two       B     f
three     C     g
four      D     h

## Series

In [12]:
pd.Series([1,2,3,4])

0    1
1    2
2    3
3    4
dtype: int64

In [13]:
pd.Series([30,40,50],index=['one','two','three'])

one      30
two      40
three    50
dtype: int64

## Reading Data File